version: '3.9'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

  db:
    image: mysql:8.1
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - laravel-db-data:/var/lib/mysql
    networks:
      - laravel-net
  app:
    volumes:
      - .:/var/www/html
      - ./resources:/var/www/html/resources
      - ./public:/var/www/html/public
volumes:
  laravel-db-data:

networks:
  laravel-net:
    driver: bridge
