version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html
    networks:
      - laravel-net
    restart: always

  app:
    image: php:8.2-fpm
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel-net
    depends_on:
      - db

  db:
    image: mysql:8.1
    container_name: laravel_db
    restart: always
    volumes:
      - laravel-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    networks:
      - laravel-net

volumes:
  laravel-db-data:

networks:
  laravel-net:
    driver: bridge
