version: '3.8'

services:
  app:
    build:
      context: ./laravel
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www
    working_dir: /var/www
    networks:
      - laravel-net
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - laravel-db-data:/var/lib/mysql
    networks:
      - laravel-net

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www
    depends_on:
      - app
    networks:
      - laravel-net

volumes:
  laravel-db-data:

networks:
  laravel-net:
    driver: bridge
