version: '3.8'

services:
  app:
    build:
      context: /root/my-laravel-project/laravel/CI-CD-Hello-PHP/laravel
    container_name: laravel_app
    depends_on:
      db:
        condition: service_started
    networks:
      - laravel-net
    volumes:
      - /root/my-laravel-project/laravel/CI-CD-Hello-PHP/laravel:/var/www:rw

  db:
    container_name: laravel_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
    networks:
      - laravel-net
    volumes:
      - laravel-db-data:/var/lib/mysql:rw

  nginx:
    container_name: laravel_nginx
    image: nginx:latest
    depends_on:
      app:
        condition: service_started
    networks:
      - laravel-net
    ports:
      - "80:80"
    volumes:
      - /root/my-laravel-project/laravel/CI-CD-Hello-PHP/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - /root/my-laravel-project/laravel/CI-CD-Hello-PHP/laravel:/var/www:rw

networks:
  laravel-net:
    driver: bridge

volumes:
  laravel-db-data:
