# Step 1: Build the app
FROM node:20-alpine AS builder

WORKDIR /app

# ننسخ فقط الملفات اللي جوا react-app
COPY react-app/package*.json ./
RUN npm install

COPY react-app ./

RUN npm run build

# Step 2: Serve with Nginx
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
