apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: react
          image: ghcr.io/momenhussein/ci-cd-hello-php:latest
          ports:
            - containerPort: 3000
