apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>
run: |
  kubectl create secret docker-registry ghcr-secret \
  docker-server=ghcr.io \
  docker-username=${{ secrets.GHCR_USERNAME }} \
  docker-password=${{ secrets.GHCR_TOKEN }} \
  docker-email=${{ secrets.GHCR_EMAIL }} \
  namespace=my-app \
  dry-run=client -o yaml > secret-ghcr.yaml
