apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: my-app
spec:
  selector:
    app: laravel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: my-app
spec:
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
