FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    zip unzip curl git nano \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www


RUN composer create-project laravel/laravel .

RUN chmod -R 775 storage bootstrap/cache

RUN composer install

EXPOSE 9000

CMD ["php-fpm"]
