FROM php:8.2-fpm

WORKDIR /var/www

COPY . ./

RUN apt-get update && apt-get install -y unzip zip git libzip-dev curl \
    && docker-php-ext-install pdo_mysql zip \
    && curl -sS https://getcomposer.org/installer | php -- \
    && mv composer.phar /usr/local/bin/composer

RUN composer install --no-interaction --optimize-autoloader

EXPOSE 9000
CMD ["php-fpm"]
