FROM php:8.1-fpm

# تثبيت الأدوات المطلوبة
RUN apt-get update && apt-get install -y unzip zip git libzip-dev curl && docker-php-ext-install pdo_mysql zip

# تثبيت Composer
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

COPY . ./

# تشغيل composer install
RUN composer install --no-interaction --optimize-autoloader

EXPOSE 9000
CMD ["php-fpm"]
