name: Generate GHCR Secret

on:
  workflow_dispatch:

jobs:
  generate-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Generate base64 of config.json
        id: encode
        run: |
          mkdir -p ~/.docker
          cat ~/.docker/config.json | base64 -w0 > encoded.txt
          echo "ENCODED_CONFIG=$(cat encoded.txt)" >> $GITHUB_ENV

      - name: Save to Kubernetes Secret YAML
        run: |
          cat <<EOF > secret-ghcr.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${ENCODED_CONFIG}
EOF

      - name: Upload YAML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghcr-secret-yaml
          path: secret-ghcr.yaml
