name: Deploy Laravel App via SSH

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/laravel-app:latest
  APP_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ vars.GHCR_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build \
          -f Dockerfile \
          --build-arg APP_ENV=${{ env.APP_ENV }} \
          -t ${{ env.IMAGE_NAME }} .

    - name: Push Docker image to GHCR
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Deploy on server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
          docker login ghcr.io -u '${{ secrets.GHCR_USERNAME }}' --password-stdin <<< '${{ secrets.GHCR_TOKEN }}' &&
          docker pull ghcr.io/${{ vars.GHCR_USERNAME }}/your-image-name:latest &&
          docker stop app || true &&
          docker rm app || true &&
          docker run -d --name app ghcr.io/${{ vars.GHCR_USERNAME }}/your-image-name:latest
        "
