name: Deploy Laravel App via SSH

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/laravel-app:latest
  APP_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Set lowercase repository name
      id: vars
      run: |
        echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"


    - name: Login to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build \
          -f Dockerfile \
          --build-arg APP_ENV=${{ env.APP_ENV }} \
          -t ghcr.io/${{ steps.vars.outputs.repo_lower }}/laravel-app:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ steps.vars.outputs.repo_lower }}/laravel-app:latest

    - name: Deploy on server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
          docker login ghcr.io -u '${{ secrets.GHCR_USERNAME }}' --password-stdin <<< '${{ secrets.GHCR_TOKEN }}' &&
          docker pull ghcr.io/${{ steps.vars.outputs.repo_lower }}/laravel-app:latest &&
          docker stop app || true &&
          docker rm app || true &&
          docker run -d --name app ghcr.io/${{ steps.vars.outputs.repo_lower }}/laravel-app:latest
        "

