name: Deploy Laravel App via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/my-laravel-project || git clone https://github.com/MomenHussein/CI-CD-Hello-PHP.git /root/my-laravel-project && cd /root/my-laravel-project
          git pull origin master
          docker-compose pull
          docker-compose up -d --build
          cd laravel
          nohup php artisan serve --host=38.242.244.34 --port=9000
