name: Deploy Laravel App via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/momenhussein/ci-cd-hello-php:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME .

    - name: Push Docker Image to GHCR
      run: |
        docker push $IMAGE_NAME

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull $IMAGE_NAME
          docker stop laravel_app || true
          docker rm laravel_app || true
          docker run -d --name laravel_app -p 80:80 $IMAGE_NAME
