name: Deploy Laravel App via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /root/my-laravel-project || git clone https://github.com/MomenHussein/CI-CD-Hello-PHP.git /root/my-laravel-project && cd /root/my-laravel-project
          git pull origin master
          docker-compose pull
          docker-compose up -d --build
