name: Deploy Laravel App via SSH

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/laravel-app:latest
  APP_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Remove Git Submodules (if any)
      run: |
        git submodule deinit -f .
        rm -rf .git/modules/*
        git rm -f CI-CD-Hello-PHP || true

    - name: Set lowercase repository name
      id: vars
      run: |
        echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

    - name: Login to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build \
          -f Dockerfile \
          --build-arg APP_ENV=${{ env.APP_ENV }} \
          -t ghcr.io/${{ steps.vars.outputs.repo_lower }}/laravel-app:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ steps.vars.outputs.repo_lower }}/laravel-app:latest

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy on server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin &&
          docker pull ghcr.io/${{ steps.vars.outputs.repo_lower }}/laravel-app:latest &&
          docker stop app || true &&
          docker rm app || true &&
          docker run -d --name app ghcr.io/${{ steps.vars.outputs.repo_lower }}/laravel-app:latest
        '
