name: Terraform Deployment

on:
  push:
    branches:
      - main
    paths:
      - terraform/**    
      - .github/workflows/terraform.yml

jobs:
  terraform:
    runs-on: ubuntu-latest

    container: 
      image: ghcr.io/momenhussein/terraform:latest
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Verify Terraform Image
        run: |
          echo "Running container image: $(terraform -version | head -n 1)"
          terraform -version

      - name: Set up Terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
